### ISSUE TITLE
create profile updated and password change successfully notification

### ISSUE THREAD

**Issue by oawoyinka** [zuri-training/project-Auth_wiki-Team-8#127]

**Comment by OluwatobilobaAbass** [comment]
https://github.com/zuri-training/project-Auth_wiki-Team-8/blob/main/frontend/profile_updated.html

https://github.com/zuri-training/project-Auth_wiki-Team-8/blob/main/frontend/css/profile_updated.css

https://github.com/zuri-training/project-Auth_wiki-Team-8/blob/main/frontend/password_changed.html

https://github.com/zuri-training/project-Auth_wiki-Team-8/blob/main/frontend/css/password_changed.css
