### ISSUE TITLE
create frequently asked question page

### ISSUE THREAD

**Issue by oawoyinka** [zuri-training/project-Auth_wiki-Team-8#128]

**Comment by Fola-flex** [comment]
#128
This was created with HTML, CSS and JS. Responsiveness was achieved by setting media queries at 800px and 460px for tablets and mobile view respectively. Also worked on the sites header, I made it responsive and fixed the scrolling issue using JS(set body overflow-y to hidden on hamburger icon click) amidst other changes. I also worked on fixing responsiveness on the created html pages. Mostly providing CSS fixes where needed and also adjusting the template to be linked to the backend(links not properly implemented and the likes).
