### ISSUE TITLE
Layout grid, Lo-fi designs

### ISSUE THREAD

**Issue by oawoyinka** [zuri-training/project-Auth_wiki-Team-8#46]
Low fidelity design link

Design arrangement for link submission which include the hi fidelity design, lo fi design, style guide and user research

**Comment by Blacmeek** [comment]
https://www.figma.com/file/U8yS7nzUSvgncbljLQVR42/Zuri-Project-Phase?node-id=0%3A1

**Comment by Blacmeek** [comment]
https://www.figma.com/file/q4lyIe3HeFY22wFikSgS5B/TEAM-8---AUTH-WIKI
