### ISSUE TITLE
Style guide/user research

### ISSUE THREAD

**Issue by oawoyinka** [zuri-training/project-Auth_wiki-Team-8#50]

**Comment by LadieKay** [comment]
https://www.figma.com/file/Ejq2QLCf1dHh2jNlgXKiaC/Project-Team-8-Design?node-id=521%3A3

**Comment by LadieKay** [comment]
I designed the style guide, conducted user research that was used for the empathy map and user flow. I also design the wireframe layout.

**Comment by LadieKay** [comment]
I also worked on the team's documentation file
[AUTH_WIKI TEAM 8 DOCUMENTATION.docx](https://github.com/zuri-training/project-Auth_wiki-Team-8/files/9331590/AUTH_WIKI.TEAM.8.DOCUMENTATION.docx)

**Comment by LadieKay** [comment]
I also worked on the user research.
[Wiki Auth Project 8 Research .pdf](https://github.com/zuri-training/project-Auth_wiki-Team-8/files/9331596/Wiki.Auth.Project.8.Research.pdf)
