### ISSUE TITLE
Style guide and finalization of the designs and prototyping

### ISSUE THREAD

**Issue by oawoyinka** [zuri-training/project-Auth_wiki-Team-8#51]

**Comment by Michaelsono** [comment]
https://www.figma.com/file/YNrZA69xjAO8vcAgIKrAyu/Untitled?node-id=8%3A723

**Comment by Michaelsono** [comment]
https://www.figma.com/file/Ejq2QLCf1dHh2jNlgXKiaC/Project-Team-8-Design?node-id=521%3A3

**Comment by Michaelsono** [comment]
https://www.figma.com/file/jQDud5Yp1Qtxt7SJrZD3UO/Personal-contributions-to-design-team-8?node-id=0%3A1
