### ISSUE TITLE
User flow

### ISSUE THREAD

**Issue by oawoyinka** [zuri-training/project-Auth_wiki-Team-8#52]

**Comment by Bemazo** [comment]
https://www.figma.com/file/Ejq2QLCf1dHh2jNlgXKiaC/Project-Team-8-Design?node-id=521%3A3

**Comment by Bemazo** [comment]
https://www.figma.com/file/q4lyIe3HeFY22wFikSgS5B/TEAM-8---AUTH-WIKI?node-id=31%3A436
https://www.figma.com/file/q4lyIe3HeFY22wFikSgS5B/TEAM-8---AUTH-WIKI?node-id=0%3A1
