### ISSUE TITLE
Kotlin, C++

### ISSUE THREAD

**Issue by oawoyinka** [zuri-training/project-Auth_wiki-Team-8#65]

**Comment by talk2bash42** [comment]
https://docs.google.com/document/d/1XoTEmu91fTJDL6PF5kdCAF5njEd-tfsbCM9bnHS0rt4/edit#

https://docs.google.com/document/d/1IFnyIKopRdBjqXXt9uOYlIr2z5SyXTL9Ch71ujCymDI/edit
